language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install coveralls
  - pip install -e .[all]
script:
  - py.test -ra -vvv --cov python_boleto python_boleto_tests
after_success: coveralls
